spring:
  profiles:
  active: local                                       # email log
  datasource:                                         # db datasource
    url: jdbc:postgresql://localhost:5432/springweb
    username: ssu
    password: 1234
  jpa:                                                # db initialization
    hibernate:
      ddl-auto: create-drop
      generate-ddl: false                             # create true
      show-sql: true                                  # sql log
    properties:
      hibernate:
        format_sql: true                              #sql query formatting

logging:
    level:
      org:
        hibernate:
          SQL: debug
          type:
            descriptor: trace                         # sql value log
        springframework:
          security: DeBug                             # spring security

external-api:
  push: ''